jaedb/Iris

- build.sh
- src/js/bootstrap.js
- src/js/components/ArtistSentence.js
- src/js/components/FollowButton.js
- src/js/components/GridItem.js
- src/js/components/List.js
- src/js/components/Thumbnail.js
- src/js/components/TrackList.js
- src/js/helpers.js
- src/js/services/lastfm/actions.js
- src/js/services/localstorage/middleware.js
- src/js/services/mopidy/actions.js
- src/js/services/mopidy/middleware.js
- src/js/services/spotify/actions.js
- src/js/services/spotify/middleware.js
- src/js/services/spotify/reducer.js
- src/js/services/ui/actions.js
- src/js/services/ui/reducer.js
- src/js/views/Album.js
- src/js/views/App.js
- src/js/views/Artist.js
- src/js/views/Playlist.js
- src/js/views/discover/DiscoverCategory.js
- src/js/views/discover/DiscoverFeatured.js
- src/js/views/discover/DiscoverNewReleases.js
- src/js/views/library/LibraryAlbums.js
- src/js/views/library/LibraryArtists.js
- src/js/views/library/LibraryLocalAlbums.js
- src/js/views/library/LibraryLocalArtists.js
- src/js/views/library/LibraryPlaylists.js
- Redesign storage engine for artists, albums and playlists
- _Much_ faster loading of assets when pre-loaded from previous request(s)
> Asset index storage

- src/js/helpers.js
- src/js/services/mopidy/actions.js
- src/js/services/mopidy/middleware.js
- src/js/services/ui/reducer.js
- src/js/views/library/LibraryLocalAlbums.js
> Local album art

- src/index.html
Favicon was 404 due to incorrect path. Added `iris/`.
> fix favicon links

- src/js/components/List.js
> Load complete local folder structure, fixes #131

- src/js/App.js
Change volume step from 10 to 5 for finer adjustment
> Volume shortcut key increments lowered to 5%

- src/js/views/Artist.js
Pretty sure you also meant to do this in https://github.com/jaedb/Iris/commit/5aaf72f852d173dae9a713fab9845cbd9286c2e3 fully? fixes https://github.com/jaedb/Iris/issues/366
> fix sorting albums on artist view

- src/js/locale/sv.yaml
This is the first version of a Swedish translation for Iris.
> Added sv.yaml

- src/js/locale/de.yaml
> German translations

- src/js/locale/dictionaries.js
- src/js/locale/fr.yaml
This PR provides french translation.
I volunteer to keep this translation up-to-date.
> Add french translation

- mopidy_iris/core.py
- mopidy_iris/frontend.py
Addresses https://github.com/jaedb/Iris/commit/564839c92b0e43a058bfbb58f4c6d39c2abf566c#r36962396 and fixes https://github.com/jaedb/Iris/issues/560
> Fixing radio + ioloop issues

- src/js/locale/dictionaries.js
> Re-enable Swedish translation

- src/js/locale/fr.yaml
This completes the missing french translation.
> Update french translation

- src/js/locale/pl.yaml
Forgot to push it last time :/
> Typo in polish translation

- src/js/locale/sv.yaml
Added missing rows and fixed spelling.
> Updated sv.yaml

- src/js/locale/en.yaml
- src/js/locale/it.yaml
Thanks for this! Awesome project!
Hereby my humble contribution.
Regards
> feature/language-it: Add Italian localization

- package-lock.json
- package.json
- src/js/views/Album.js
- src/js/views/Artist.js
- src/scss/views/_album.scss
- src/scss/views/_artist.scss
> Fix biography rendering

- src/js/services/genius/actions.js
> Filtered lyrics

- src/assets/icons/jellyfin.svg
- src/js/components/Icon.js
- src/js/locale/en.yaml
- src/js/util/helpers.js
- src/js/util/selectors.js
Hello,
Here's a small contribution implementing Jellyfin sources in the media browser.
Depends on jellyfin/mopidy-jellyfin#117 for the playlists.
Have a good day !
> Implement Jellyfin source

- mopidy_iris/frontend.py
> Add setting access guard to fix 824

- src/js/locale/ru.yaml
- src/scss/components/_context-menu.scss
- src/scss/components/_dropdown-field.scss
- src/scss/components/_header.scss
- src/scss/components/_sidebar.scss
- src/scss/global/_core.scss
- src/scss/global/_forms.scss
- src/scss/global/_variables.scss
Overpass font doesn't support Cyrillic chars so need to use backup font.
BEFORE:
AFTER:
UPD: Also fixed some RU localization. Some things were missing and some things looked weird for native speaker
> FIX: Fonts for Cyrilic languages

- src/js/locale/br.yaml
> Criado uma tradução em pt_BR

- mopidy_iris/system.py
> Get use sudo from env var

- mopidy_iris/system.sh
> Add support for env var for IRIS_CONFIG_LOCATION

- src/js/locale/br.yaml
- Updated common and reusable phrases for clarity and consistency.
- Checked and corrected any grammatical errors.
- Ensured that the language file aligns with the Brazilian Portuguese.
> Update Portuguese language file and corrected grammatical errors

- src/js/locale/it.yaml
> Update Italian localization
