jaedb/Iris

- src/js/views/library/LibraryAlbums.js
When album list is sorted by some attribute it is not possible to restore default sort order (by artist). This pull requests adds ability to sort by artists.
> Add option to sort albums by artists

- src/js/components/VolumeControl.js
This implements #100.
For some reason, volume sometimes seems to have value of `true`, which causes drops to 0/1%, but this really seems like a problem with backend/some other part of UI, displayed only when sending multiple volume change requests.
> Add mouse wheel support in VolumeControl bar

- src/js/components/Dater.js
> padding for when seconds == 0

- mopidy_iris/core.py
Looks like there was a breaking API change at some point (https://docs.mopidy.com/en/latest/api/core/#mopidy.core.TracklistController.get_length); this line was giving me exceptions.
> Change .length to .get_length()

- Dockerfile
Everything seems to work well using your Dockerfile, except from trying to upgrade Iris using the UI. That's because `sudo` isn't installed it seems.
> adds sudo package to the Docker file

- mopidy_iris/system.sh
``[[ $flag ]]`` checks if the variable is not empty. Not if it's true or false. Which means it will always succeed, because both possible values (``true`` and ``false``) are not empty.
An alternative would be ``[[ "$flag" = "true" ]]``.
Fixes some points mentioned in #489. Doesn't address changing `pip` to `pip3` (or maybe even ``python3 -m pip``) or the missing detection of the version number.
> Fix checking the boolean flag

- src/js/services/lastfm/actions.js
With this pull request, artist biographies are first requested in the user preferred language. If the returned content is empty and the preferred language isn't English, a second try is made with no language specified.
Was discussed in issue #621.
> Translated bios

- src/js/services/spotify/actions.js
When `getPlaylistTracks` was called with with `forceRefetch = true`  (by clicking the refresh button in the playlist view), only the first page would get the refresh query parameter appended.
This patch appends the refresh query parameter to all subsequent requests as well
> Fix bug with refreshing playlists where only the first page would be refreshed

- Dockerfile
Resolves #648. Switching to Alpine would be nicer and even smaller but impossible currently due to libspotify.
The resulting image size with this Dockerfile is 1.66GB, where the current one from Docker hub is 2.43GB.
> Switch Docker image to official Debian image

- docker/entrypoint.sh
On the Wiki, I would also add a sixth list item under ¨Getting-started > To install using Docker¨ to explain the new functionality:
6. If you want to sideload additional PIP packages to your Docker container, these can be specified using the `PIP_PACKAGES` environment variable, demarcated by a space between different packages
> Update docker/entrypoint.sh to allow for sideloading of PIP packages (e.g. additional mopidy plugins)

- Dockerfile
I am not sure if there is a specific reason to clone the full repository inside `Dockerfile`. 
If not, with `git clone --depth 1`, the docker image size can be reduced from 1000MB to 500MB.
This will create a shallow clone, which is primarily useful for builds, not development.
> Use 'git clone --depth 1' to reduce docker image size from 1GB to 500MB

- src/js/views/Library/Tracks.js
"album" was used instead, probably a mistake.
> (Trivial) use music_note icon for tracks page

- .gitignore
- src/js/components/TrackList.js
Closes #861
I also updated package-lock.json, because it was desynchronized for some reason, and added `/build/` to .gitignore, as `pip install --user .` creates that directory.
> Fix selection ordering

- src/js/util/selectors.js
Add Tidal source for tracks. Build is needed after merging PR.
> Add Tidal source for Tracks

- Dockerfile
Hi James, 
I roughly adapted the Dockerfile from my repo to your current development state:
- Moved the build process of the GStreamer plugins to a separate stage. 
- Restructured the file a bit and cleaned up some (probably) unused dependencies.
With this multistage feature, you can achieve much smaller Docker images.
Maybe this is an approach you want to adopt :-)
> Updated Dockerfile with multi-stage build approach

- src/js/App.js
- src/js/components/SearchResults.js
- src/js/views/Search.js
- src/scss/components/_grid.scss
- src/scss/components/_images.scss
- src/scss/components/_sub-tabs.scss
- src/scss/global/_core.scss
- src/scss/views/_search.scss
- Remove filtering of sources
- Migrate search to functional component(s)
> Search refactor

- docker/entrypoint.sh
Some pip packages may get updates and subsequent container runs wouldn't install them. Not so much of a problem normally but when for example yt-dlp is installed through pip to use with mopidy-youtube it's important to keep yt-dlp up-to-date to not have functionality be broken when Youtube updates their webpage again
> feat(docker): also update the specified pip packages rather than just installing them

- Dockerfile.alpine
- docker/entrypoint.sh
It gets all it's dependencies (Mopidy, Mopidy-Spotify) from the Alpine Linux repositories.
For reference the image sizes:
- Debian, 1.49GB
- Alpine, 832MB
> Add an Alpine Linux-based Docker image

- Dockerfile
These versions work in Alpine Linux and the master branch of the mopidy-spotify branch (besides the new support being merged at all) has some new fixes as well.
> Switch Dockerfile to use a released gst-plugins-rs and master mopidy-spotify branch

- mopidy_iris/system.sh
Adds an `fi` to an if statement block - was causing issues with running commands in `system.sh` (e.g. `local_scan`), both via web UI and terminal.
> Fix typo in system.sh script

- src/js/locale/de.yaml
In german the plural of tracks is the same as singular: "Titel"
> fix DE Titeln

- Dockerfile
Should fix the pipeline failing to build the Docker image.
> fix(docker): correct git clone command for retrieving mopidy-spotify

- .github/workflows/ci.yml
It's a bit hard for me to test this one, but this should do the job.
> feat(docker): build both amd64 and arm64 images, and an Alpine-based one

- src/js/util/helpers.js
- src/js/util/selectors.js
* Display the playlists provided by the [Mopidy-Subidy](https://github.com/Prior99/mopidy-subidy) and [Mopidy-WebM3U](https://github.com/mgoltzsche/mopidy-webm3u) extensions in addition to the ones provided by the built-in M3U plugin.
* Show artists and albums from the [Mopidy-Subidy](https://github.com/Prior99/mopidy-subidy) backend (served by a Subsonic server).
> Add Subidy and WebM3U support

- src/js/components/SearchResults.js
- src/js/views/Search.js
Implemented 'as loaded' search by quite simply not sorting the results.
Resolves #933
I have only tested this with a single source of Spotify, so might be an good idea to test with multiple different sources to make sure it works before merging.
> Add 'as loaded' sort ordering

- src/js/util/format.js
Switch to RFC 4648 Base 64 Encoding with URL and Filename Safe Alphabet. https://en.wikipedia.org/wiki/Base64#Variants_summary_table
https://datatracker.ietf.org/doc/html/rfc4648#section-5
Before this change certain Mopidy backend URIs when encoded contained forward slashes. The forward slashes prevented those URIs from being loaded.
Fixes #984
Rebased and re-tested version of #983
> Use RFC 4648 section 5 URL-safe Base64 for URL encoding
